[package]
name = "age-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = { version = "0.9.1", features = ["async"] }
anyhow = "1.0.71"
